### ISSUE TITLE
DevParana na Estrada 2019

### ISSUE THREAD

**Issue by ezidio** [ezidio/devparana-na-estrada#1]
DevParana na Estrada

Submissão de palestras para as edições do DevParana na Estrada.

Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Votação
Os organizadores de cada cidade irão definir as palestras que serão apresentadas conforme a disponibilidade de slots disponíveis.

Formato:

```
**Qual seu nome?**
Everton Tavares

**Possui Twitter?, usaremos para divulgar**
@ezidio 

**Palestras**

Exemplo de título
> Descrição da minha palestra 

Outra palestra
> Descrição da minha palestra 

**Cidades que posso apresentar**
- [ ] 09/05 - Maringá
- [ ] 13/05 - Umuarama
- [x] 14/05 - Cianorte
- [ ] 16/05 - Curitiba (Caso estiver na cidade neste dia.)
- [ ] 20/05 - Campo Mourão
- [ ] 22/05 - Londrina
- [x] 27/05 á 31/05 - Toledo, Cascavel e Foz do Iguaçu (Precisa ter disponibilidade de viagem)

```

**Comment by leonardoelias** [comment]
**Qual seu nome?**
Leonardo Elias

**Possui Twitter?, usaremos para divulgar**
@leonardoelias_

Perceived Performance ou como fazer sua aplicação se sentir mais rápida
> Performance é UX. Quem te fala se seu site está rápido ou não é o usuário. Velocidade depende mais da percepção do usuário que do número medido no cronômetro.

**Cidades que posso apresentar**
- [ ] 09/05 - Maringá
- [X] 13/05 - Umuarama
- [x] 14/05 - Cianorte
- [ ] 16/05 - Curitiba (Caso estiver na cidade neste dia.)
- [X] 20/05 - Campo Mourão
- [X] 22/05 - Londrina
- [x] 27/05 á 31/05 - Toledo, Cascavel e Foz do Iguaçu (Precisa ter disponibilidade de viagem)

**Comment by rhnonose** [comment]
**Qual seu nome?**
Rodrigo Nonose

**Possui Twitter?, usaremos para divulgar**
@backendwizard

**Palestras**
- From Sync to Async: how Elixir educated me - Buenos Aires Erlang & Elixir Factory Lite - [conf page with video/slides](http://www.erlang-factory.com/eflba2017/rodrigo-nonose)
- Microservices with Elixir - Code BEAM SF - [website](https://codesync.global/conferences/code-beam-sf-2019/)/[slides](http://rhnonose.github.io/microservices_elixir.pdf)
- Programação Funcional na Web com Elixir e Elm - DevParaná Conf - [website](https://www.devparana.org/conf/)/[slides](http://rhnonose.github.io/prog_funcional_web.pdf)
- Functional Programming in the Web with Elixir and Elm in - [website](http://rubyconf.com.br/)/[video](https://www.eventials.com/locaweb/functional-programming-in-the-web-with-elixir-and-elm-com-rodrigo-nonose/)/[slides](http://rhnonose.github.io/prog_funcional_web_rubyconf.pdf)
- Serverless não é o caminho - GDG DevFest [website](https://devfestpr.com/)/[slides](http://rhnonose.github.io/serverless.pdf)
- A Síndrome do Impostor - inga.js - [slides](http://rhnonose.github.io/sindrome_impostor.pdf)
- Até onde vai o Backend - BEMUG - [slides](http://rhnonose.github.io/onde_vai_back.pdf)
- Carreira em Desenvolvimento - [slides](http://rhnonose.github.io/carreira_dev.pdf)
- Contribuindo para Open Source - [slides](http://rhnonose.github.io/open_source.pdf)
- Introdução a Elixir - BEMUG - [slides](http://rhnonose.github.io/elixir_intr.pdf)
- Introdução a Elm - Programação Funcional no Frontend - FEMUG - [slides](http://rhnonose.github.io/elm_intr.pdf)
- Microserviços - Como dar um tiro no próprio pé - BEMUG - [slides](http://rhnonose.github.io/microservices.pdf)
- Orientação a objetos ou Funcional - BEMUG - [slides](http://rhnonose.github.io/oo_fp.pdf)
- Next.js - React Meetup - [slides](http://rhnonose.github.io/next_js.pdf)

**Cidades que posso apresentar**
- [x] 09/05 - Maringá
- [x] 13/05 - Umuarama
- [x] 14/05 - Cianorte
- [ ] 16/05 - Curitiba (Caso estiver na cidade neste dia.)
- [x] 20/05 - Campo Mourão
- [x] 22/05 - Londrina
- [ ] 27/05 á 31/05 - Toledo, Cascavel e Foz do Iguaçu (Precisa ter disponibilidade de viagem)

**Comment by ezidio** [comment]
**Qual seu nome?**
Everton Tavares

**Possui Twitter?, usaremos para divulgar**
@ezidio 

**Palestras**

Arquiteturas orientadas a eventos
> Apesar de ser algo que tem sido utilizado e comentado amplamente nos últimos anos, não existe uma definição definitiva sobre o que é arquitetura orientada a eventos.
> O que é? Como faz?
> Essa palestra tem por objetivo mostrar as formas que eventos são aplicados nas arquiteturas atuais, e demostrar isso através de exemplos práticos.

Monolith First: Uma abordagem.
> São muitos os benefícios que uma arquitetura de microsserviços traz para a aplicação. Porém para uma pequena aplicação, ou uma grande aplicação em seu estágio inicial, pode ser que essa abordagem traga algumas desvantagens.
> Essa palestra tem por objetivo apresentar uma abordagem de implementação que possa colaborar para de aplicações moniliticas, dando a ela um mindset de microsserviços.

**Cidades que posso apresentar**
- [x] 09/05 - Maringá
- [ ] 13/05 - Umuarama
- [ ] 14/05 - Cianorte
- [ ] 16/05 - Curitiba (Caso estiver na cidade neste dia.)
- [ ] 20/05 - Campo Mourão
- [x] 22/05 - Londrina
- [x] 27/05 á 31/05 - Toledo, Cascavel e Foz do Iguaçu (Precisa ter disponibilidade de viagem)

**Comment by geovanisouza92** [comment]
**Qual seu nome?**
Geovani de Souza

**Possui Twitter?, usaremos para divulgar**
@geovanisouza92 

**Palestras**

O último framework que você vai aprender
> Um estudo sobre aplicação de DDD na vida real

Código como risco
> Um estudo sobre como resolver bugs através de refatoração 

**Cidades que posso apresentar**
- [x] 09/05 - Maringá
- [x] 13/05 - Umuarama
- [x] 14/05 - Cianorte
- [ ] 16/05 - Curitiba (Caso estiver na cidade neste dia.)
- [x] 20/05 - Campo Mourão
- [x] 22/05 - Londrina
- [ ] 27/05 á 31/05 - Toledo, Cascavel e Foz do Iguaçu (Precisa ter disponibilidade de viagem)
